ALTER TABLE "Campaign"
ADD COLUMN IF NOT EXISTS "description" TEXT,
ADD COLUMN IF NOT EXISTS "status" TEXT NOT NULL DEFAULT 'SCHEDULED',
ADD COLUMN IF NOT EXISTS "category" TEXT NOT NULL DEFAULT 'PRICE',
ADD COLUMN IF NOT EXISTS "ruleType" TEXT NOT NULL DEFAULT 'BASE_PRICE',
ADD COLUMN IF NOT EXISTS "audience" TEXT NOT NULL DEFAULT 'ALL',
ADD COLUMN IF NOT EXISTS "startAt" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "endAt" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "priority" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "autoApply" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN IF NOT EXISTS "stackable" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "fixedAdultPriceMXN" INTEGER,
ADD COLUMN IF NOT EXISTS "fixedChildPriceMXN" INTEGER,
ADD COLUMN IF NOT EXISTS "fixedInfantPriceMXN" INTEGER,
ADD COLUMN IF NOT EXISTS "discountPercent" INTEGER,
ADD COLUMN IF NOT EXISTS "payQty" INTEGER,
ADD COLUMN IF NOT EXISTS "takeQty" INTEGER,
ADD COLUMN IF NOT EXISTS "minAdults" INTEGER,
ADD COLUMN IF NOT EXISTS "minChildren" INTEGER,
ADD COLUMN IF NOT EXISTS "minInfants" INTEGER,
ADD COLUMN IF NOT EXISTS "maxUses" INTEGER,
ADD COLUMN IF NOT EXISTS "usedCount" INTEGER NOT NULL DEFAULT 0;

CREATE INDEX IF NOT EXISTS "Campaign_packageId_idx"
ON "Campaign"("packageId");

CREATE INDEX IF NOT EXISTS "Campaign_isActive_idx"
ON "Campaign"("isActive");

CREATE INDEX IF NOT EXISTS "Campaign_status_idx"
ON "Campaign"("status");

CREATE INDEX IF NOT EXISTS "Campaign_startAt_idx"
ON "Campaign"("startAt");

CREATE INDEX IF NOT EXISTS "Campaign_endAt_idx"
ON "Campaign"("endAt");

CREATE INDEX IF NOT EXISTS "Campaign_packageId_status_startAt_endAt_idx"
ON "Campaign"("packageId", "status", "startAt", "endAt");